project:
  type: website

execute: 
  freeze: auto
  echo: false
  warning: false

website:
  title: "sarah.fyi"
  search: false
  site-url: https://sarah.fyi
  repo-url: https://github.com/sj-io/sarahFYI
  navbar:
    title: false
    background: none
    left:
      - href: index.qmd
        icon: house-fill
        text: " "
      - href: about.qmd
        icon: person-arms-up
        text: " "
      - icon: controller
        href: gaming/index.qmd
        text: " "
        aria-label: "gaming"
      - icon: image
        href: screenies/index.qmd
        text: " "
  body-footer: <script data-goatcounter="https://sarahfyi.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: false
    page-layout: full



