project:
  type: website

website:
  title: "sarah.fyi"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: false
    page-layout: full



