project:
  type: website

execute: 
  freeze: auto

website:
  title: "sarah.fyi"
  search: false
  site-url: https://sarah.fyi
  repo-url: https://github.com/sj-io/sarahFYI
  navbar:
    title: false
    background: none
    left:
      - href: index.qmd
        icon: house-fill
        text: " "
      - href: about.qmd
        icon: person-arms-up
        text: " "
      - icon: car-front-fill
        href: mk8dx/index.qmd
        text: " "
        aria-label: "mario kart"
      - icon: image
        href: screenies/index.qmd
        text: " "
    body-footer: <script data-goatcounter="https://sarahfyi.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: false
    page-layout: full



