project:
  type: website

website:
  title: "sarah.fyi"
  search: false
  navbar:
    title: false
    background: none
    left:
      - href: index.qmd
        icon: house-fill
        text: " "
      - href: about.qmd
        icon: person-arms-up
        text: " "
      - icon: car-front-fill
        href: mk8dx/index.qmd
        text: " "
        aria-label: "mario kart"

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: false
    page-layout: full



