project:
  type: website

execute: 
  freeze: auto
  echo: false
  warning: false

website:
  title: "sarah.fyi"
  search: false
  site-url: https://sarah.fyi
  repo-url: https://github.com/sj-io/sarahFYI
  navbar:
    title: false
    background: none
    left:
        # home
      - href: index.qmd
        icon: house-fill
        text: " "
        # about
      - href: about.qmd
        icon: person-arms-up
        text: " "
        # gaming
      # - href: gaming/index.qmd
        # aria-label: "gaming"
      - icon: controller
        menu: 
          - href: gaming/index.qmd
          - href: gaming/mkw/tt/index.qmd
          - href: gaming/mkw/stats/index.qmd
          - href: gaming/mk8dx/speedruns/48-track.qmd
        text: " "
        # scrapbook
      - icon: image
        href: screenies/index.qmd
        text: " "
  body-footer: <script data-goatcounter="https://sarahfyi.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

#format:
 # html:
    # theme: custom.scss
    # css: styles.css
  #  toc: false
   # page-layout: full



